name: "ci build"
on:
  workflow_dispatch:
  push:
    branches:
     - master
     - ci
  pull_request:
    branches:
     - master
     - ci

jobs:
  build-1:    
    runs-on: ubuntu-latest
    steps:      
       uses: actions/checkout@v3
     - name: "Build 1"
       uses: actions/upload-artifact@v3
       with:
         name: artifact-1
         path: ./files/1-banner.d/build/

  test:
    runs-on: ubuntu-latest
    needs: build-1
    steps:
    - uses: actions/checkout@v3
    - name: "Download Builded Artifact"
      uses: actions/download-artifact@v3.0.1
      with:
        name: artifact-1
    - name: "Tests-1"
      run: |
           pwd
           chmod +x ./Banner
           ./Banner

  docker-img:
    runs-on: ubuntu-latest
    needs: test
    name: "Docker IMG Builder"
    steps:
    - uses: actions/checkout@v3
    - name: "Download Builded, Tested Artifact"
      uses: actions/download-artifact@v3.0.1
      with:
        name: artifact-1
    - name: "Build Docker Image"
      uses: docker/build-push-action@v3
      with:
        username: ${{github.actor}}  
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: aluvium/github-actions-for-packages/c_plusplus
        tag_with_sha: true
