name: "ci build"
on:
  workflow_dispatch:
  push:
    branches:
     - master
     - ci
  pull_request:
    branches:
     - master
     - ci

jobs:
  build-1:    
    runs-on: 
     - ubuntu-latest
    steps:      
     - name: "Checkout Code"
       uses: actions/checkout@v3
     - name: "Build 1"
       uses: actions/upload-artifact@v3
       with:
         name: artifact-1
         path: ./files/1-banner.d/build/
