name: Build
on:
  push:
    branches:
     - master

jobs:
  build:    
    runs-on: 
     - ubuntu 20.04
  steps:
   - name: "-Check-"          
     uses: actions/checkout@v3
   - name: "-HelloWord-"
     uses: ./.github/actions/hello
