name: Build
on:
  workflow_dispatch:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master

jobs:
  release:    
    runs-on: 
     - ubuntu-latest
    steps:      
     - name: "Checkout Code"
       uses: actions/checkout@v3
     - name: "Build 1"
       uses: ./files/1-banner.d
       with: 
         file: ./Dockerfile
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
