name: Build
on:
  push:
    branches:
     - master

jobs:
  build:    
    runs-on: 
     - ubuntu-latest
    steps:      
     - uses: actions/checkout@v3
     - name: "HelloWord"
       uses: ./.github/actions/hello/
